app:
  calc:
    add:
      value1: 12
      value2: 13
    subs:
      value1: 12
      value2: 13
  prop:
    employee-map:
      kemalal:
        address:
          city: istanbul
          street: besiktas
        first-name: kemal
        height: 190
        last-name: alaz
        weight: 80
      osmanyay:
        address:
          city: istanbul
          street: cekemkoy
        first-name: osman
        height: 200
        last-name: yaycioglu
        weight: 95
    employee-template:
      address:
        city: istanbul
        street: atasehir
      first-name: employee
      height: 200
      last-name: surname
      weight: 100
    employees:
    - address:
        city: istanbul
        street: kadikoy
      first-name: osman
      height: 199
      last-name: alaz
      weight: 90
    - address:
        city: ankara
        street: mamak
      first-name: ali
      height: 180
      last-name: veli
      weight: 69
    execute-timeout: 100
    language: tr
    language-prefix: Turkce
    locations:
    - istanbul
    - ankara
    - izmir
    name: my application
greets:
  goodbye:
    prefix: Goodbye
  hello:
    prefix: Hello
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
server:
  port: 9090
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
spring:
  profiles:
    active:
    - live
    default: live
  datasource:
    username: postgres
    password: ENC(cU+yC/GZAye2Fl7bdHsfenv8H9War5qZIqlJv1YoLIFQdhPO9l28hZf+BNIJ5RXb)
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        show_sql: true
        format_sql: true
  data:
    mongodb:
      database: bays
      host: localhost
      port: 27017
